name: Go

on:
  pull_request:
    paths-ignore:
      - "**.md"

concurrency:
  group: go-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    name: make check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - run: make check-no-lint

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.13
